# Generated by Django 3.1.5 on 2021-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeGroupInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField()),
                ('hot', models.BooleanField()),
                ('status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=32)),
                ('update_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'meme_group_info',
            },
        ),
        migrations.CreateModel(
            name='MemeGroupRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meme_group_code', models.CharField(max_length=32)),
                ('meme_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'meme_group_relation',
            },
        ),
        migrations.CreateModel(
            name='MemeGroupTagRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meme_group_code', models.CharField(max_length=32)),
                ('tag_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'meme_group_tag_relation',
            },
        ),
        migrations.CreateModel(
            name='MemeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField()),
                ('img_type', models.CharField(max_length=16)),
                ('img_md5', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('resource_url', models.TextField()),
                ('resource_key', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=32)),
                ('update_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'meme_info',
            },
        ),
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('remark', models.TextField()),
            ],
            options={
                'db_table': 'tag_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('emile', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=32)),
                ('meme_code', models.CharField(max_length=32)),
                ('remark', models.TextField()),
                ('active', models.BooleanField()),
                ('gender', models.CharField(max_length=2)),
                ('birthday', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserStarRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=32)),
                ('meme_group_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_star_relation',
            },
        ),
    ]
