# Generated by Django 3.1.5 on 2021-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20210306_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memegroupinfo',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='created_by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='hot',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memegroupinfo',
            name='updated_by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegrouprelation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memegrouprelation',
            name='meme_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegrouprelation',
            name='meme_group_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegrouptagrelation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memegrouptagrelation',
            name='meme_group_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memegrouptagrelation',
            name='tag_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='created_by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='img_md5',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='img_type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='resource_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='resource_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='status',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='memeinfo',
            name='updated_by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='meme_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nick',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userstarrelation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userstarrelation',
            name='meme_group_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userstarrelation',
            name='user_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
