# Generated by Django 3.1.5 on 2021-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20210329_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memegroupinfo',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
